# Generated by Django 5.0.4 on 2025-03-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
